providers = ["node"]
[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[variables]
PORT = "3000"
NODE_ENV = "production"
HOST = "0.0.0.0"        # Ensure binding to all interfaces

[start]
cmd = "npm start"
