providers = ["node"]
[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[variables]
PORT = "3000"
NODE_ENV = "production"

[start]
cmd = "node -e 'console.log(\"Starting server on port \" + process.env.PORT); import(\"./build/server/index.js\").then(module => module.default())'"
